---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: marley
    environment: dev
  name: marley
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marley
  template:
    metadata:
      labels:
        app: marley
        version: 0.0.3-sha-9c18782
    spec:
      containers:
      - image: ghcr.io/caju-rocks/marley:sha-9c18782
        imagePullPolicy: IfNotPresent
        name: marley
