---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: marley
    environment: dev
  name: marley
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: marley
  type: ClusterIP 
